// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk-ivf4mkp4kr0tEeJ3ZiJaXEku2-5wWU',
    appId: '1:387386573650:web:bf778d8b15b2e9d454308b',
    messagingSenderId: '387386573650',
    projectId: 'phcash-a8f69',
    authDomain: 'phcash-a8f69.firebaseapp.com',
    storageBucket: 'phcash-a8f69.firebasestorage.app',
    measurementId: 'G-2BYPBMN9XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYvkErdpa5X1gBExlUgafMTWlOEv_bGh4',
    appId: '1:387386573650:android:8c37d501e805fad754308b',
    messagingSenderId: '387386573650',
    projectId: 'phcash-a8f69',
    storageBucket: 'phcash-a8f69.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU8XXtLHbdaxsHOYFeqUITDwITQBMUz0Q',
    appId: '1:387386573650:ios:543a2e4e207f7fff54308b',
    messagingSenderId: '387386573650',
    projectId: 'phcash-a8f69',
    storageBucket: 'phcash-a8f69.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk-ivf4mkp4kr0tEeJ3ZiJaXEku2-5wWU',
    appId: '1:387386573650:web:0872d9ca0471adb754308b',
    messagingSenderId: '387386573650',
    projectId: 'phcash-a8f69',
    authDomain: 'phcash-a8f69.firebaseapp.com',
    storageBucket: 'phcash-a8f69.firebasestorage.app',
    measurementId: 'G-V165XCYT81',
  );
}
